#ifndef OPCODES_H
#define OPCODES_H

// DEFINE SPECIAL OPCODES FOR LIBRARY 0

#define OP_EXITRPL         0   // TERMINATES RPL EXECUTION
#define OP_BREAKPOINT      1   // STOP RPL EXECUTION

// ADD MORE HERE




#endif // OPCODES_H
