#ifndef FIRMWARE_H
#define FIRMWARE_H

// INCLUDE ALL USB EARLY TO ALLOW OVERRIDING SOME CONSTANTS IN target_xxx HEADERS
#include <usb.h>

// REDEFINE SOME CONSTANTS FOR THE VARIOUS TARGETS
#include <target.h>

#endif // FIRMWARE_H
