/*
 * Copyright (c) 2014-2015, Claudio Lapilli and the newRPL Team
 * All rights reserved.
 * This file is released under the 3-clause BSD license.
 * See the file LICENSE.txt that shipped with this distribution.
 */


#ifndef ERRORCODES_H
#define ERRORCODES_H

// THIS HEADER EXPORTS ALL KNOWN MESSAGE CODES IN USE
// LIBRARIES USE THE ERROR CODES, THE EXTERNAL UI PROVIDES
// TRANSLATABLE TEXT FOR EACH OF THESE MESSAGES
// THE RPL CORE DOES NOT PROVIDE A TEXT MESSAGE

// MESSAGE ID'S ARE ENCODED USING SINT NUMBER BY THE MACRO MAKEMSG(lib,error)

// LIBRARY 0 IS USED FOR BASIC SYSTEM MESSAGES (COMPILER ERRORS, ETC.)
// THAT DON'T BELONG TO ANY LIBRARY IN PARTICULAR
// ALL OTHER ERRORS SHOULD BE ASSIGNED TO THEIR RESPECTIVE LIBRARIES

enum AllMessages {

    // PROGRAM EXECUTION ERRORS
    //ERR_PROGRAMEXPECTED = MAKEMSG(SECO,0),

    // COMPILER/DECOMPILER AND GENERAL CORE ERRORS

    // THESE ARE SYSTEM EXCEPTIONS, DO NOT CHANGE THE ORDER
    // ORDER NUMBER MUST MATCH THE EXCEPTION BIT NUMBER

    // IDENTIFIERS AND VARIABLES
    //ERR_IDENTEXPECTED = MAKEMSG(DOIDENT,0),
    //ERR_UNDEFINEDVARIABLE = MAKEMSG(DOIDENT,1),
    //ERR_CIRCULARREFERENCE = MAKEMSG(DOIDENT,2),

    // SYMBOLICS
    ERR_SYMBOLICEXPECTED = MAKEMSG(DOSYMB,0),
    ERR_NOTAVALIDRULE = MAKEMSG(DOSYMB,1),
    ERR_INVALIDUSERDEFINEDFUNCTION = MAKEMSG(DOSYMB,2),

    // MATRIX
    ERR_MATRIXEXPECTED = MAKEMSG(DOMATRIX,0),
    ERR_INVALIDDIMENSION = MAKEMSG(DOMATRIX,1),
    ERR_NOTALLOWEDINMATRIX = MAKEMSG(DOMATRIX,2),
    ERR_INCOMPATIBLEDIMENSION = MAKEMSG(DOMATRIX,3),
    ERR_MATRIXORREALEXPECTED = MAKEMSG(DOMATRIX,4),
    ERR_SQUAREMATRIXONLY = MAKEMSG(DOMATRIX,5),
    ERR_VECTOREXPECTED = MAKEMSG(DOMATRIX,6),
    ERR_MISPLACEDBRACKETS = MAKEMSG(DOMATRIX,7),

    // FLAGS
    // TRANSCENDENTAL FUNCTIONS
//    ERR_ARGOUTSIDEDOMAIN = MAKEMSG(66,0),


//    ERR_ = MAKEMSG(  ,  ),


};








#endif // ERRORCODES_H

