#ifndef ERRORCODES_H
#define ERRORCODES_H

// THIS HEADER EXPORTS ALL KNOWN ERROR CODES IN USE
// LIBRARIES USE THE ERROR CODES, THE EXTERNAL UI PROVIDES
// TRANSLATABLE TEXT FOR EACH OF THESE ERRORS
// THE RPL CORE DOES NOT PROVIDE A TEXT MESSAGE

// ERROR CODES ARE OPCODES OF THE LIBRARY LIBERROR
// THEY ARE ENCODED USING SINT NUMBER BY THE MACRO MKERROR(lib,error)

// LIBRARY 0 IS USED FOR BASIC SYSTEM MESSAGES (COMPILER ERRORS, ETC.)
// THAT DON'T BELONG TO ANY LIBRARY IN PARTICULAR
// ALL OTHER ERRORS SHOULD BE ASSIGNED TO THEIR RESPECTIVE LIBRARIES

enum AllErrors {
    ERR_EXITRPL = MKERROR(DOCOL,0),
    ERR_BKPOINT = MKERROR(DOCOL,1),
    ERR_NOTALLOWEDINSYMBOLICS = MKERROR(0,1),
    ERR_ENDWITHOUTSTART = MKERROR(0,2),
    ERR_MISSINGBRACKET = MKERROR(0,3),
    ERR_BADARGCOUNT = MKERROR(0,4),
    ERR_SYNTAXERROR = MKERROR(0,5),
    ERR_INVALIDTOKEN = MKERROR(0,6),
    ERR_STARTWITHOUTEND = MKERROR(0,7),
    ERR_MALFORMEDOBJECT = MKERROR(0,8),
    ERR_INVALIDOPERATORINSYMBOLIC = MKERROR(0,9)



//    ERR_ = MKERROR(  ,  ),


};








#endif // ERRORCODES_H

