/*
 * Copyright (c) 2014, Claudio Lapilli and the newRPL Team
 * All rights reserved.
 * This file is released under the 3-clause BSD license.
 * See the file LICENSE.txt that shipped with this distribution.
 */

#include <firmware.h>
#include "sysvars.h"

// EXTERNAL RPL MACHINE REGISTERS

// MEMORY REGIONS. EACH MEMORY REGION CAN GROW INDEPENDENTLY
// GROWTH MAY TRIGGER A GC IF INSUFFICIENT MEMORY.

// TEMPOB AND TEMPBLOCKS

word_p TempOb DATAORDER1;  // TEMPORARY OBJECT STORAGE
word_p *TempBlocks DATAORDER1;     // TEMPOB BLOCK POINTERS STORAGE
word_p *TempBlocksEnd DATAORDER1;  // END OF THE TEMPOB BLOCKS
int32_t TempBlocksSize DATAORDER1;

// GLOBAL ARRAY OF POINTERS THAT ARE TO BE UPDATED BY THE GC
word_p GC_PTRUpdate[MAX_GC_PTRUPDATE] DATAORDER1;

// RETURN STACK

word_p *RStk DATAORDER2;   // BASE OF RETURN STACK
word_p *RSTop DATAORDER2;  // TOP OF THE RETURN STACK
word_p *HaltedRSTop DATAORDER2;    // RETURN STACK OF HALTED PROGRAM
int32_t RStkSize DATAORDER2;   // TOTAL SIZE OF RETURN STACK

// DATA STACK

word_p *DStk DATAORDER2;   // BASE OF DATA STACK
word_p *DSTop DATAORDER2;  // TOP OF THE DATA STACK
int32_t DStkSize DATAORDER2;   // TOTAL SIZE OF DATA STACK
word_p *DStkBottom DATAORDER2;     // BASE OF THE CURRENT STACK
word_p *DStkProtect DATAORDER2;    // BASE OF THE PROTECTED STACK

// DIRECTORIES

word_p *Directories DATAORDER2;    // BASE OF DIRECTORY STORAGE
word_p *DirsTop DATAORDER2;        // POINTER TO END OF USED DIRECTORIES
int32_t DirSize DATAORDER2;
word_p *CurrentDir DATAORDER2;     // POINTER TO CURRENT DIRECTORY

// LAMS

word_p *LAMs DATAORDER2;   // BASE OF LOCAL VARIABLES STORAGE
word_p *LAMTop DATAORDER2; // TOP OF THE LAM STACK
int32_t LAMSize DATAORDER2;
word_p *nLAMBase DATAORDER2;       // START OF THE LAST LAM ENVIRONMENT
word_p *LAMTopSaved DATAORDER2;    // SAVED VALUE OF LAMTOP USED DURING COMPILATION
word_p *HaltedLAMTop DATAORDER2;   // TOP OF THE LAM STACK
word_p *HaltednLAMBase DATAORDER2; // START OF THE LAST LAM ENVIRONMENT

// TWO MORE SECTIONS AVAILABLE FOR FUTURE USE: DATAORDER3 AND DATAORDERLAST

// *************************************************************
// ** END OF VARIABLES THAT NEED TO BE AT PERSISTENT LOCATION
// ** ACROSS FIRMWARE UPDATES / WARMSTART / RESET
// *************************************************************

// ALL OTHER VARIABLES CAN CHANGE LOCATION, AS THEY ARE REINITIALIZED DURING WARMSTART

// LIBRARIES
LIBHANDLER LowLibRegistry[MAXLOWLIBS];
LIBHANDLER SysHiLibRegistry[MAXSYSHILIBS];
LIBHANDLER HiLibRegistry[MAXHILIBS];
int32_t HiLibNumbers[MAXHILIBS];
int32_t NumHiLibs;

// OTHER RPL CORE VARIABLES THAT ARE NOT AFFECTED BY GC
WORD CurOpcode; // CURRENT OPCODE (WORD)
WORD HWExceptions, Exceptions, TrappedExceptions;       // FLAGS FOR CURRENT EXCEPTIONS
WORD BreakPtFlags;      // FLAGS FOR HARDWARE BREAK POINTS
WORD ErrorCode, TrappedErrorCode;
WORD GCFlags;   // INTERNAL REGISTER TO INDICATE SPECIAL CONDITIONS, LIKE A GARBAGE COLLECTION HAPPENED
word_p *ValidateTop;   // TEMPORARY DATA AFTER THE RETURN STACK USED DURING COMPILATION
word_p *ValidateBottom;        // TEMPORARY DATA AFTER THE RETURN STACK USED DURING COMPILATION
word_p *ErrornLAMBase; // SAVED BASE OF LAM ENVIRONMENT AT ERROR HANDLER
word_p *ErrorLAMTop;   // SAVED VALUE OF LAMTOP AT ERROR HANDLER
word_p *ErrorRSTop;    // SAVED TOP OF RETURN STACK AT ERROR HANDLER

// ARGUMENTS TO PASS TO LIBRARY HANDLERS
// DURING COMPILATION
uint32_t ArgNum1, ArgNum2, ArgNum3, RetNum;

// MULTIPRECISION LIBRARY CONTEXT
// INCLUDES STORAGE FOR REAL REGISTERS
DECIMAL_CONTEXT Context;

// TEMPORARY SCRATCH MEMORY FOR DIGITS
int32_t RDigits[EXTRA_STORAGE];
// PREALLOCATED STATIC REAL NUMBER REGISTERS FOR TEMPORARY STORAGE
REAL RReg[REAL_REGISTERS];

int32_t int32_t2RealIdx;
