/*
 * Copyright (c) 2014, Claudio Lapilli and the newRPL Team
 * All rights reserved.
 * This file is released under the 3-clause BSD license.
 * See the file LICENSE.txt that shipped with this distribution.
 */

#include <firmware.h>
#include "sysvars.h"

// EXTERNAL RPL MACHINE REGISTERS

// MEMORY REGIONS. EACH MEMORY REGION CAN GROW INDEPENDENTLY
// GROWTH MAY TRIGGER A GC IF INSUFFICIENT MEMORY.

// TEMPOB AND TEMPBLOCKS

WORDPTR TempOb DATAORDER1;  // TEMPORARY OBJECT STORAGE
WORDPTR *TempBlocks DATAORDER1;     // TEMPOB BLOCK POINTERS STORAGE
WORDPTR *TempBlocksEnd DATAORDER1;  // END OF THE TEMPOB BLOCKS
BINT TempBlocksSize DATAORDER1;

// GLOBAL ARRAY OF POINTERS THAT ARE TO BE UPDATED BY THE GC
WORDPTR GC_PTRUpdate[MAX_GC_PTRUPDATE] DATAORDER1;

// RETURN STACK

WORDPTR *RStk DATAORDER2;   // BASE OF RETURN STACK
WORDPTR *RSTop DATAORDER2;  // TOP OF THE RETURN STACK
WORDPTR *HaltedRSTop DATAORDER2;    // RETURN STACK OF HALTED PROGRAM
BINT RStkSize DATAORDER2;   // TOTAL SIZE OF RETURN STACK

// DATA STACK

WORDPTR *DStk DATAORDER2;   // BASE OF DATA STACK
WORDPTR *DSTop DATAORDER2;  // TOP OF THE DATA STACK
BINT DStkSize DATAORDER2;   // TOTAL SIZE OF DATA STACK
WORDPTR *DStkBottom DATAORDER2;     // BASE OF THE CURRENT STACK
WORDPTR *DStkProtect DATAORDER2;    // BASE OF THE PROTECTED STACK

// DIRECTORIES

WORDPTR *Directories DATAORDER2;    // BASE OF DIRECTORY STORAGE
WORDPTR *DirsTop DATAORDER2;        // POINTER TO END OF USED DIRECTORIES
BINT DirSize DATAORDER2;
WORDPTR *CurrentDir DATAORDER2;     // POINTER TO CURRENT DIRECTORY

// LAMS

WORDPTR *LAMs DATAORDER2;   // BASE OF LOCAL VARIABLES STORAGE
WORDPTR *LAMTop DATAORDER2; // TOP OF THE LAM STACK
BINT LAMSize DATAORDER2;
WORDPTR *nLAMBase DATAORDER2;       // START OF THE LAST LAM ENVIRONMENT
WORDPTR *LAMTopSaved DATAORDER2;    // SAVED VALUE OF LAMTOP USED DURING COMPILATION
WORDPTR *HaltedLAMTop DATAORDER2;   // TOP OF THE LAM STACK
WORDPTR *HaltednLAMBase DATAORDER2; // START OF THE LAST LAM ENVIRONMENT

// TWO MORE SECTIONS AVAILABLE FOR FUTURE USE: DATAORDER3 AND DATAORDERLAST

// *************************************************************
// ** END OF VARIABLES THAT NEED TO BE AT PERSISTENT LOCATION
// ** ACROSS FIRMWARE UPDATES / WARMSTART / RESET
// *************************************************************

// ALL OTHER VARIABLES CAN CHANGE LOCATION, AS THEY ARE REINITIALIZED DURING WARMSTART

// LIBRARIES
LIBHANDLER LowLibRegistry[MAXLOWLIBS];
LIBHANDLER SysHiLibRegistry[MAXSYSHILIBS];
LIBHANDLER HiLibRegistry[MAXHILIBS];
BINT HiLibNumbers[MAXHILIBS];
BINT NumHiLibs;

// OTHER RPL CORE VARIABLES THAT ARE NOT AFFECTED BY GC
WORD CurOpcode; // CURRENT OPCODE (WORD)
WORD HWExceptions, Exceptions, TrappedExceptions;       // FLAGS FOR CURRENT EXCEPTIONS
WORD BreakPtFlags;      // FLAGS FOR HARDWARE BREAK POINTS
WORD ErrorCode, TrappedErrorCode;
WORD GCFlags;   // INTERNAL REGISTER TO INDICATE SPECIAL CONDITIONS, LIKE A GARBAGE COLLECTION HAPPENED
WORDPTR *ValidateTop;   // TEMPORARY DATA AFTER THE RETURN STACK USED DURING COMPILATION
WORDPTR *ValidateBottom;        // TEMPORARY DATA AFTER THE RETURN STACK USED DURING COMPILATION
WORDPTR *ErrornLAMBase; // SAVED BASE OF LAM ENVIRONMENT AT ERROR HANDLER
WORDPTR *ErrorLAMTop;   // SAVED VALUE OF LAMTOP AT ERROR HANDLER
WORDPTR *ErrorRSTop;    // SAVED TOP OF RETURN STACK AT ERROR HANDLER

// ARGUMENTS TO PASS TO LIBRARY HANDLERS
// DURING COMPILATION
UBINT ArgNum1, ArgNum2, ArgNum3, RetNum;

// MULTIPRECISION LIBRARY CONTEXT
// INCLUDES STORAGE FOR REAL REGISTERS
DECIMAL_CONTEXT Context;

// TEMPORARY SCRATCH MEMORY FOR DIGITS
BINT RDigits[EXTRA_STORAGE];
// PREALLOCATED STATIC REAL NUMBER REGISTERS FOR TEMPORARY STORAGE
REAL RReg[REAL_REGISTERS];

BINT BINT2RealIdx;
