#include <ui.h>
// SYSTEM GLOBAL VARIABLES, MAPPED TO RAM 0X08004000 (8 KBYTES MAXIMUM!)
// THESE VARIABLES ARE NOT PERSISTENT ACROSS ON/OFF, REBOOT, ETC.
// VARIABLES CANNOT HAVE STATIC INITIAL VALUES, MUST BE INITIALIZED BY SOFTWARE.


// BASIC HAL VARIABLES
HALSCREEN halScreen;


// CPU SPEED HIGH LEVEL
BINT halFlags;
HEVENT halBusyEvent;




// KEYBOARD DRIVER, HIGH LEVEL


// COMMAND LINE EDITOR

